{
 "title": "Golden Signals",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requisições por segundo",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "http_requests_duration_seconds_total:sum_irate",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Taxa de erro",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Error rate" }
   ],
   "targets": [
    {
     "expr": "http_requests_duration_seconds_error_rate",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Latência média das requisições",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "http_requests_duration_seconds_latencia_media",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}